mahoganyhomes: porting the plugin
Owain94/OpenOSRS-RL-hub pull request #167
Opened 2020-09-09 04:45 UTC by grian32

hoping i didnt fuck up anything lmao

2020-09-09 10:32 UTC, Lucwousin requested changes
tiny modernizr type things

2020-09-09 10:32 UTC, Lucwousin commented on mahoganyhomes/src/main/java/net/runelite/client/plugins/mahoganyhomes/Home.java
> +	private static final ImmutableSet<Integer> LADDERS;
ImmutableSet is deprecated, use Set.of

2020-09-09 10:32 UTC, Lucwousin commented on mahoganyhomes/src/main/java/net/runelite/client/plugins/mahoganyhomes/Hotspot.java
> +	private static final ImmutableMap<Integer, Hotspot> HOTSPOT_BY_OBJECT_ID;
Same idea as before

2020-09-09 10:50 UTC, grian32 commented on mahoganyhomes/src/main/java/net/runelite/client/plugins/mahoganyhomes/Hotspot.java
> +	private static final ImmutableMap<Integer, Hotspot> HOTSPOT_BY_OBJECT_ID;
done i think

2020-09-09 10:50 UTC, grian32 commented on mahoganyhomes/src/main/java/net/runelite/client/plugins/mahoganyhomes/Home.java
> +	private static final ImmutableSet<Integer> LADDERS;
done i think

2020-09-30 05:14 UTC, grian32 commented
from my understanding the devs are making their own
and since > 21 days ago
im pretty sure im right
gonna close this

2020-09-30 17:27 UTC, merged